version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html/laravel
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: armes_de_paris
      DB_USERNAME: postgres
      DB_PASSWORD: secret

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: armes_de_paris
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./weapons-front:/app
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - app
